language: python

env:
  - R_LIBS_USER=~/R

install:
  - sudo apt-add-repository -y ppa:marutter/rdev
  - sudo apt-get update
  - sudo apt-get install r-base-dev libxml2-dev libcurl4-gnutls-dev qpdf texinfo texlive-latex-extra texlive-fonts-recommended texlive-fonts-extra
  - "[ ! -d ~/R ] && mkdir ~/R"
  - R --version
  - R -e '.libPaths(); sessionInfo()'
  - Rscript -e 'install.packages("rplos", dep = TRUE, repos = "http://cran.rstudio.org")'

script:
  - make install
  - make check